### ISSUE TITLE
Gateway Time-out error when uploading 100k entities at once.

### ISSUE THREAD

**Issue by srujner** [getodk/central#694] opened 2024-08-02 11:57 UTC
#### Problem description
504 Gateway error occurs when trying to upload 100k entities at once. The list of entities is available, but it is not possible to Append data.

#### URL of the page
https://staging.getodk.cloud/#/projects/51/entity-lists/entities_100k/entities

#### Steps to reproduce the problem

1. Navigate to the link above
2. Click on the choose one button;
3. Attach [entities_100k_test.csv](https://github.com/user-attachments/files/16470018/entities_100k_test.csv) file
4. Click on the Append Data button;
5. Wait till the processing is over

#### Screenshot
![Screenshot(117)](https://github.com/user-attachments/assets/7a30508f-51eb-4652-860b-3bb2ab15f185)

#### Expected behavior
Entities should upload without any errors

#### Central version shown in version.txt
e49518adb84f88d7bc6c3626fc77584dfc935435 (v2024.1.0-6-ge49518a)
+c1ad0f39ccc61a8e67a45afe942588d6681ddc5c client (v2024.1.0-33-gc1ad0f39)
+fb96aa3333d3442ea43365755766262f21de3969 server (v2024.1.0-23-gfb96aa33)

#### Browser version
Firefox 128.0

#### Other information
Looks like the issue is only on frontend, because backend managed to add all entities correctly
![Screenshot(118)](https://github.com/user-attachments/assets/0e18f1a7-3eea-4ad2-8813-118eaed1ac07)

**Comment by lognaturel** [comment] 2024-09-10 04:50
Duplicate of #691

**Closed by lognaturel** 2024-09-10 04:50 UTC
