### ISSUE TITLE
Long names of edited properties don’t truncate in the Entity Detail page, Activity part

### ISSUE THREAD

**Issue by dbemke** [getodk/central#566] opened 2023-12-15 11:03 UTC
#### Problem description
Long names of edited properties don’t truncate in the Entity Detail page, Activity part. On the production server the edited properties truncate and are different colour.
#### URL of the page
https://test.getodk.cloud/
#### Steps to reproduce the problem
1. Go to a form creating entities.
2. Go to the Entities page – Data tab.
3. Hover over an entity in the table of entities and click "More”.
4. Click the edit button and enter a long name in a property field and update the entity.
5. Check the Activity section – "Data updated by …”.
#### Screenshot
test.getodk.cloud
![testtruncateProperty](https://github.com/getodk/central/assets/56479916/fda89a4c-4864-4ed0-a11e-8589e5b16a87)
vs production.getodk.cloud
![procuctionTruncate](https://github.com/getodk/central/assets/56479916/c013affe-1bf3-4f78-9548-37b800518e47)

#### Expected behavior
Edited properties with long names should truncate also in the Activity section. I'm not sure what is the expected now- should the colour of edited properties be green and red or black?
#### Central version shown in version.txt
versions:
58b81c6babc13923ac9f8c07ef698a391250d825 (v2023.4.0-9-g58b81c6)
+60b2b8c58017f4bc5320e9da26d33ae3beb054cc client (v2023.4.0-56-g60b2b8c5)
+222a183333a1e4d5968f42636b73bb9f8e88274f server (v2023.4.0-62-g222a1833)

#### Browser version
Chrome 119.0.6045.159 (64-bit), Firefox 120.0 (64-bit)

**Comment by matthew-white** [comment] 2023-12-15 21:13
> Long names of edited properties don’t truncate in the Entity Detail page, Activity part.

This is actually the expected behavior right now. If the old value or the new value is long, then it should wrap rather than truncate. We set it up that way in case the value contains a line break. Previously, you couldn't see line breaks in the old or new values. I left a comment related to this on the release criteria [here](https://docs.google.com/document/d/1EdEDcXoJmrryFYNc56zciuQ82G_iVGBQf1UFEkWiUtw/edit?disco=AAABBBulYYA). That said, the old or new value should never spill over its cell: a long word should be forced to wrap instead of overflowing into another cell of the table or outside the table.

Note that the first column (the property name, `last_name` above) should not wrap, because a property name doesn't contain line breaks. A long property name should be truncated with an ellipsis.

> I'm not sure what is the expected now- should the colour of edited properties be green and red or black?

The old and new values should always be black. If the property name (e.g., `last_name`) is a conflicting property, then it should be red; otherwise, it should be black.

**Comment by matthew-white** [comment] 2023-12-18 21:15
I'm going to go ahead and close this issue for now, but let me know if you have other questions or encounter any problems related to this issue.

**Closed by matthew-white** 2023-12-18 21:15 UTC
Labels: frontend, entities
