### ISSUE TITLE
Authentication error after trying to submit a form from copied Enketo url from a different user

### ISSUE THREAD

**Issue by dbemke** [getodk/central#491] opened 2023-09-21 09:22 UTC
#### Problem description
There is an authentication error after trying to submit a form from copied Enketo url from a different user account.

#### Steps to reproduce the problem
1. Go to the staging server and log in (account 1).
2. Go to submissions page and click "+New" to open Enketo view.
3. Copy the Enketo url.
4. Open a different browser/ incognito mode/ browser as a guest (so that you're not logged in to account 1).
5. Paste the url.
6. Log in to a different account than the first one and submit the form.
#### Screenshot
![authError](https://github.com/getodk/central/assets/56479916/1c4f7934-6d82-4f8e-ad23-a57f1bab33cd)

#### Central version shown in version.txt
https://staging.getodk.cloud/
versions:
0a310c619750d64519c4ce9883e08d124020975b (v2023.3.1-13-g0a310c6)
+972062f259293877ca2f718aefc83ad80979f2ca client (v2023.3.0-35-g972062f2)
+0b1272fb9935bd256f42b7debb63c48b1bd7a35f server (v2023.3.1-70-g0b1272fb)

**Comment by dbemke** [comment] 2023-09-21 11:12
The second account I used to submit the user was a Project Viewer

**Comment by srujner** [comment] 2023-09-21 12:00
Additional notes: 

I tried to reproduce the issue on Staging but I've got a little bit different results.

I Created a submission and copied the Enketo URL on Firefox on Account 1.
Then I opened Google Chrome where I was already logged into Account 2 (No additional roles, user without admin rights)
and I saw that error:
![Screenshot from 2023-09-21 13-09-03](https://github.com/getodk/central/assets/85225519/c0a48214-105b-4e8a-ac9d-f50d98bb945e)

So I've got the authentication error right from the start not after clicking on the Submit button. 

I compare the behavior on test.getodk.cloud and there was no errors at all.
We didn't have any test cases where you open link on users with different account rights/roles so we haven't encountered this before. Also we did **not** use public links.

Overall I think that authentication error should be shown in that case (maybe with a little bit different text in the dialog) and a different user should not be able to submit the submission when the link to it is not public. Unless every link copied from the browser is immediately treated as public?

Tell us what do you think about this case.

**Comment by matthew-white** [comment] 2023-09-21 16:30
This is an interesting series of cases, I think it's great you're looking into this area.

> Unless every link copied from the browser is immediately treated as public?

For form drafts, Enketo links should be accessible by anyone with the link even if they don't have a Central account. That's because someone without a Central account might be asked to provide input about a form draft. However, for published forms, Enketo links should not accessible by anyone with the link. They should only be accessible by sitewide administrators and users with a role in the project. Note that if a published form also has a draft, it is two different Enketo links, and access should work differently for each. One more detail: users with a Data Collector role on the project shouldn't be able to access a form if it is in the closed state (unless they're somehow a sitewide administrator).

The second error message ("The form does not exist or you no longer have access to it.") is what is shown to someone who is logged into Central, but who does not have access to the form. If you aren't a sitewide administrator, and you also have no role in the project, then this is the message you should see. I think this message corresponds to a 404 error. What happens is that Enketo asks Central for the form in order to display it, but because the user doesn't have access to the form, Central responds that it can't find it.

On the other hand, if you're allowed to view the form, but not submit to it, then you see a different error message (the first one above, "Authentication required."). That's only the case when you're a project viewer in the project (and not a sitewide administrator). In that case, Enketo asks Central for the form in order to display it. Central is happy to comply, because project viewers are allowed to view forms. But then when Enketo asks Central to accept the submission, Central refuses, because project viewers aren't allowed to submit. I think that's expected. In Central, if you're a project viewer, we show links to preview the form, but not submit to it, because we know that submitting won't work and that it'll be a confusing experience.

> (the issue doesn’t occur on https://test.getodk.cloud/)

> I compare the behavior on test.getodk.cloud and there was no errors at all.

This part of the issue is surprising. At the moment, test.getodk.cloud and staging are at the same version of Central, so you'd think that the behavior would be the same.

I went to the following page to take a look at the behavior: https://test.getodk.cloud/#/projects/389/forms/all-widgets/submissions. I copied the link from the + New button, then pasted it into an incognito window. I was prompted to log in to Central, which is what I'd expect. Do you see the same thing? Do you think differences in roles could explain the behavior you saw on test.getodk.cloud?

**Comment by dbemke** [comment] 2023-09-22 07:09
You're right. I checked again with different project roles (admin vs. project viewer) and the result on test.getodk.cloud are the same.

**Comment by matthew-white** [comment] 2023-12-20 05:51
I'm going to go ahead and close this issue, but let me know if you are still seeing problems in this area.

**Closed by matthew-white** 2023-12-20 05:51 UTC
Labels: backend
