### ISSUE TITLE
Passphrase not required after first encrypted submissions

### ISSUE THREAD

**Issue by dbemke** [getodk/central#493] opened 2023-09-21 14:12 UTC
#### Problem description
The decryption passphrase field doesn’t appear after clicking "Download x submissions” if the user is on the Submission tab and adds first encrypted submissions and doesn’t refresh the page.

#### Steps to reproduce the problem
1. In an encrypted project go to Submissions tab of a form and click "+New" and submit the form.
2. Go to Submissions tab click "Refresh” button (don’t refresh the page).
3. Click "Download x submissions” (passphrase is not required).
4. Refresh the page.
5. Click "Download x submissions” (passphrase is required).

#### Expected behavior
The passphrase should be required before downloading submissions.
#### Central version shown in version.txt
https://test.getodk.cloud/
versions:
0a310c619750d64519c4ce9883e08d124020975b (v2023.3.1-13-g0a310c6)
+972062f259293877ca2f718aefc83ad80979f2ca client (v2023.3.0-35-g972062f2)
+0b1272fb9935bd256f42b7debb63c48b1bd7a35f server (v2023.3.1-70-g0b1272fb

#### Browser
Firefox and Chrome

**Comment by matthew-white** [comment] 2023-09-21 15:37
This issue is similar to #461 insomuch as the root cause is getodk/central-frontend#521 in both cases. I've slotted getodk/central-frontend#521 for .5, so I'm hoping we'll be able to resolve that soon. I'm going to go ahead and close this issue, but it's now linked from getodk/central-frontend#521. It's helpful to have these up-to-date repro steps.

**Closed by matthew-white** 2023-09-21 15:37 UTC
