### ISSUE TITLE
Entities forms containing duplicate properties - unable to upload a new version of the form

### ISSUE THREAD

**Issue by dbemke** [getodk/central#841] opened 2024-12-10 08:29 UTC
#### Problem description
After testing properties there are entities forms (in my projects on Central) which contain properties e.g "p", "P" ( the form containing these properties was added before the change in #769). I'm not able to upload a new version of this form - when I click "create draft" there's info "The entity definition within the form is invalid. Multiple Form Fields cannot be saved to a single property." 
#### URL of the page
https://staging.getodk.cloud/#/projects/101/forms/movie%20entities
#### Steps to reproduce the problem
1. Go to the form containing duplicate properties which were added before changes in #769
https://staging.getodk.cloud/#/projects/101/forms/movie%20entities
2. Click "Create a new draft” 
#### Screenshot
![propertySameDraft](https://github.com/user-attachments/assets/e1838417-469a-4002-8ed9-f0cc2fbb05ce)

#### Expected behavior
It should be possible to add a new version of a form. I'm not sure what is the expected result when the properties are already in the dataset - should they be removed somehow?
#### Central version shown in version.txt
https://staging.getodk.cloud/
versions:
0f7bad611df1329b3de3305674903a44ee21d011 (v2024.2.1-9-g0f7bad6)
+f0d4725d7ee1c9bce7c27be94ee3e7823921b7ed client (v2024.2.1-56-gf0d4725d)
+4355d9e4c3a0f7bb6b694aad4cf318145905da2e server (v2024.2.0-114-g4355d9e4)

**Comment by matthew-white** [comment] 2024-12-11 21:35
@lognaturel, what do you think is the expected behavior in this case? As of #769, if a user has an existing entity list with properties "p" and "P", then they are able to upload and publish a form definition that saves to either "p" or "P", but not both. Is that an acceptable restriction? I think it's possible that some users may have accidentally created properties like "p" and "P", and I think we've accounted for that case. However, I sort of doubt that they'd intentionally want to use both in the same form.

**Comment by matthew-white** [comment] 2024-12-11 21:40
Just to be clear about the implications of this issue:

- If someone did have such a form, it would prevent managed encryption from being enabled on the project, since that process creates new form versions.
- Similarly, it wouldn't be possible to make changes to the XForm in a migration (e.g., for #692). (The migration as a whole wouldn't fail, but a form like this wouldn't be migrated. It would stay the same.)

**Comment by lognaturel** [comment] 2024-12-11 22:00
> Is that an acceptable restriction?

Yes, I think so. Regardless, before we try to do anything more sophisticated I think we should wait to see whether it's a real state that a user has gotten into.

**Comment by matthew-white** [comment] 2024-12-11 22:01
Sounds good, I'll go ahead and close the issue. @dbemke, let us know if you have any questions or if there's something else that you think we should explore for this issue.

**Closed by matthew-white** 2024-12-11 22:01 UTC
Labels: backend, entities
