### ISSUE TITLE
User is seeing a backend message after trying to edit the submission that has closed or closing state

### ISSUE THREAD

**Issue by srujner** [getodk/central#613] opened 2024-03-15 10:56 UTC
#### Problem description
Backend request is visible for the users instead of user friendly message.

#### URL of the page
https://staging.getodk.cloud/v1/projects/79/forms/multi%20warning/submissions/uuid%3A92604e98-6ea7-416a-9361-82fab90f3cde/edit

#### Steps to reproduce the problem
1. Have at least one form in the project;
2. Send Submission for a form;
3. Navigate to the Form Access tab and change status of the form for Closing or Closed;
4. Go back to Submission page and click on the Edit button 

#### Screenshot
![Screenshot(46)](https://github.com/getodk/central/assets/85225519/2e77e453-d3ee-46b4-84e8-41548b4e19e4)

#### Expected behavior
User friendly message should be visible

#### Central version shown in version.txt
106f533a128d43bb71ff2366bf2d07ff23082b38 (v2023.5.1-2-g106f533)
+00d84096788bbf31bd4ca903449848e8fd177159 client (v2023.5.0-34-g00d84096)
+e610ed1f41c1b04777c1779500c92d4cfea17ed0 server (v2023.5.0-30-ge610ed1f)

#### Browser version
Firefox 123.0.1

#### Around when did you see the problem (in UTC)?
10:10 AM UTC

**Comment by matthew-white** [comment] 2024-03-16 22:38
We're hoping to fix the root cause at some point so that users are able to edit submissions to closed or closing forms. There's been related discussion at getodk/central-backend#469. However, it hasn't been an easy fix so far, and I don't think we plan to address it in the very near future. In the meantime, I agree that it'd be nice to prevent the user from seeing this message from Backend. How about we disable the submission edit button if the form is closed or closing and show an informative tooltip? That's what we do for the form preview button, which faces the same restriction.

**Comment by matthew-white** [comment] 2024-11-11 04:00
This issue happens because of how Enketo communicates with Central. Once we replace Enketo with Web Forms, this won't be an issue anymore. After discussing this issue with @lognaturel, I think we should hold off on making this change, as we would have to revert or modify it once we further integrate Web Forms into Central. I'm going to go ahead and close the issue for now, but we can reopen it if we hear about more users being affected by it. Thank you for filing the issue, @srujner!

**Closed by matthew-white** 2024-11-11 04:00 UTC
Labels: bug, frontend
